### ISSUE TITLE
pipeline without ERCC

### ISSUE THREAD

**Issue by kevin199011** [jw156605/SingleSplice#2]
Hi, I'm working on single cell RNA-seq samples that do not have ERCC in it. I was wondering if the SingleSplice pipeline also works in this case? Thank you!

Kevin

**Comment by jw156605** [comment]
Hi Kevin,

Unfortunately, SingleSplice only works with ERCC spike-ins (or in principle
any type of spike-in that has enough different concentrations to allow
noise model estimation). Other papers have used the profiles of all
endogenous genes to estimate technical noise, but I haven't tested this,
and am not sure how well it would work. Cole Trapnell's group just
published a method called Census that can perform normalization without
spike-ins, so you could try that. The downside of their approach is that it
tries to infer differential isoform usage for full-length isoforms, which
in general you can't do reliably from short read data.

Best,
Josh
